version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - weather-report
        - temperature-service
        - precip-service
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # application
  #weather-report:
    #image: weather-report
    #container_name: weather-report
    #build:
      #context: ./weather_report
    #depends_on:
        #- temperature-service
        #- precip-service
    #ports:
      #- 8080:80
    #restart: on-failure
